FROM node:lts-alpine

WORKDIR "/app"

COPY package.json .
RUN npm config set strict-ssl false
RUN npm install --force --loglevel verbose, logging level

COPY . .

CMD ["npm", "run", "start"]
